// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spllvpofdxpojevcyxfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwbGx2cG9mZHhwb2pldmN5eGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NTg0NzAsImV4cCI6MjA2OTMzNDQ3MH0.ILXC-jG7hPZg_o70aBqGMOs5NTyqIuTDhNaaXyFa6Y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});